# Neural Networks (EEE950)
# Pedro Vinicius A. B. de Venancio

# Clear workspace
rm(list=ls())
# Clear all plots
graphics.off()
# Clear console
cat("\014")

# Import library
library(latex2exp)

# Load algorithm library
source('perceptron.R')

# Synthetic linearly separable data points

# Interesting case studies: set seed as 3, 7, 10, 19
set.seed(3) 
# Number of samples
n_samples <- 150
x <- seq(0, 2*n_samples, length = n_samples)

# Samples generated by a normal distribution
x1 <- rnorm(n_samples, mean = 650, sd = 120)
x2 <- rnorm(n_samples, mean = 600, sd = 120)

# Scatter plot
plot(x, x2, xlab = TeX('x_1'), ylab = TeX('x_2'), col = 'blue', xlim = c(-100, 1000), ylim = c(-100, 1000))
points(x1, x, col = 'red')

# Input matrix
X <- cbind(x, x2)
X <- rbind(X, cbind(x1, x))

# Bias
bias <- seq(1, 1, length = n_samples)
X <- cbind(bias, X)
colnames(X) <- c('x0', 'x1', 'x2')

# Output vector
Y <- c(seq(0, 0, length = n_samples), seq(1, 1, length = n_samples))

# Find weights that fit the data with the perceptron algorithm
W <- perceptron(X, Y, eta = 0.01, max_epochs = 10)

# Plot decision boundary
decision_boundary(X, W)
