# Neural Networks (EEE950)
# Pedro Vinicius A. B. de Venancio
# Extreme Learning Machines (ELMs)

# X: input matrix with dimension (n_samples * proportion) x (n_features + 1)
# W_1: Hidden layer weights with dimension (n_features+1) x n_neurons
# W_2: Output layer weights with dimension n_neurons x 1
# Y: labels vector with dimension (n_samples * proportion) x 1
# Y_hat: predictions vector with dimension (n_samples * proportion) x 1
# n_neurons: number of neurons from hidden layer
# proportion: percentage used to split data into training and test sets

# Import libraries
library(ggplot2)
library(latex2exp)
library(corpcor)

# Training algorithm of extreme learning machines
elm <- function(X, Y, n_neurons){
  
  # Number of samples
  n_samples <- dim(X)[1]
  # Number of features
  n_features <- dim(X)[2]
  
  # Random weights of hidden layer (n_features x n_neurons)
  W_1 <- matrix(runif(n_features, min = -0.5, max = 0.5), nrow = n_features, ncol = n_neurons)
  W_1 <- replicate(n_neurons, runif(n_features, -0.5, 0.5))

  # Mapping from input layer to hidden layer (n_samples x n_neurons)
  A_1 <- tanh(X %*% W_1)

  # Compute weights of output layer (n_neurons x 1)
  W_2 <- pseudoinverse(A_1) %*% Y

  # Predictions: mapping from hidden layer to output layer (n_samples x 1)
  Y_hat <- A_1 %*% W_2

  return(list(W_1, W_2, Y_hat))
  
}

# Contour function
contour_plot2D <- function(X, W_1, W_2, axis_lim, step = 0.1){
  
  # Number of samples
  n_samples <- dim(X)[1]
  
  # Make grid
  grid <- seq(axis_lim[1], axis_lim[2], step)
  grid_size <- length(grid)
  
  # Contour generated by extreme learning machine
  contour <- matrix(nrow = grid_size, ncol = grid_size)
  A_1 <- cbind(1)
  for (i in 1:grid_size){
    for(j in 1:grid_size){
      x1 <- grid[i]
      x2 <- grid[j]
      x1x2 <- as.matrix((cbind(1, x1, x2)))
      A_1 <- tanh(x1x2 %*% W_1)
      contour[i,j] <- sign(A_1 %*% W_2)
    }
  }
  
  # Contour plot from a grid of points
  persp(grid, grid, contour)
  contour(grid, grid, contour, xlim = c(axis_lim[1], axis_lim[2]), ylim = c(axis_lim[1], axis_lim[2]), xlab = TeX('x_1'), ylab = TeX('x_2'), nlevels = 1)
  # Plot data
  points(X[1:n_samples/2, 2], X[1:n_samples/2, 3], col = 'blue')
  points(X[(n_samples/2+1):n_samples,2], X[(n_samples/2+1):n_samples, 3], col = 'red')
  
}